# Generated by Django 6.0.3 on 2026-04-02 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnggotaKelompok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('npm', models.CharField(max_length=20, unique=True)),
                ('prodi', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto_anggota/')),
                ('angkatan', models.CharField(blank=True, max_length=10)),
                ('role', models.CharField(blank=True, default='Anggota', max_length=50)),
                ('motto', models.TextField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('urutan', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Anggota Kelompok',
                'verbose_name_plural': 'Anggota Kelompok',
                'ordering': ['urutan', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='GlobalTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#6366f1', max_length=7)),
                ('secondary_color', models.CharField(default='#8b5cf6', max_length=7)),
                ('accent_color', models.CharField(default='#06b6d4', max_length=7)),
                ('bg_color', models.CharField(default='#0f0f1a', max_length=7)),
                ('text_color', models.CharField(default='#e2e8f0', max_length=7)),
                ('card_bg', models.CharField(default='#1e1e35', max_length=7)),
                ('font_family', models.CharField(default='Space_Grotesk', max_length=50)),
                ('card_layout', models.CharField(default='grid', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Global Theme',
            },
        ),
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#6366f1', max_length=7)),
                ('secondary_color', models.CharField(default='#8b5cf6', max_length=7)),
                ('accent_color', models.CharField(default='#06b6d4', max_length=7)),
                ('bg_color', models.CharField(default='#0f0f1a', max_length=7)),
                ('text_color', models.CharField(default='#e2e8f0', max_length=7)),
                ('card_bg', models.CharField(default='#1e1e35', max_length=7)),
                ('font_family', models.CharField(choices=[('Space_Grotesk', 'Space Grotesk'), ('Outfit', 'Outfit'), ('Sora', 'Sora'), ('DM_Sans', 'DM Sans'), ('Nunito', 'Nunito'), ('Raleway', 'Raleway'), ('Josefin_Sans', 'Josefin Sans'), ('Quicksand', 'Quicksand')], default='Space_Grotesk', max_length=50)),
                ('card_layout', models.CharField(choices=[('grid', 'Grid'), ('masonry', 'Masonry'), ('list', 'List')], default='grid', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
